steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$banded-object-438816-p9/flask-app:v2', '.']

  # Step 2: Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$banded-object-438816-p9/flask-app:v2']

  # Step 3: Update the Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'flask-instance', '--zone=us-central1-a', '--command', 'sudo docker pull gcr.io/$Pbanded-object-438816-p9/flask-app:v2 && sudo docker stop $(sudo docker ps -q) && sudo docker run -d -p 5000:5000 gcr.io/$Pbanded-object-438816-p9/flask-app:v2']
