options:
  logging: CLOUD_LOGGING_ONLY  # or NONE

steps:
  # Your steps to build the Docker container, push to GCR, and reset the instance
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$banded-object-438816-p9/flask-app:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$banded-object-438816-p9/flask-app:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'reset'
      - 'flask-instance'
      - '--zone=us-central1-a'

images:
  - 'gcr.io/$banded-object-438816-p9/flask-app:$COMMIT_SHA'
